import math
T=int(input())
ans1=[]
ans2=[]
for i in range(100000,T):
    n=i+1
    N=n
    x=(n)*(n+1)/2
    j=0
    if(x%2==1):
        j=0
    else:
        t=n*n+n
        t/=2
        k=int(math.sqrt(t))
        if ((k)*(k)+k)>t:
            k=k-1
        t=k
        z=int(t*(t+1)/2)
        y=int(x/2)
        if(z== x/2):
            p=n-t
            a=(t)*(t-1)/2
            b=p*(p+1)/2
            j=int(a+b)
        else:
            j=n-t
    ans1=j
    n=N
    x=(n)*(n+1)/2
    if(x%2==1):
        j=0
    else:
            j=0
            s=0
            t=x/2
            while(s<t):
                s+=n
                j+=1
                n-=1
            if(s==t):
                z=N-j
                p=j
                a=(z)*(z-1)/2
                b=p*(p-1)/2
                j+=int(a+b)
    ans2=j
    print(N)
    if(ans1!=ans2):
        print(N,ans1,ans2)
        break